import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

/// Available avatars. Each one is identified by a stable [id] (e.g.
/// `avatar_01`). The legacy emoji avatars from the first MVP keep working
/// because [AvatarImage] falls back to a Text widget for non-asset ids.
class FigusAvatar {
  final String id;
  final String label;
  final bool proOnly;

  const FigusAvatar({
    required this.id,
    required this.label,
    required this.proOnly,
  });

  /// SVG asset path. Only valid for cartoon avatars (id starts with `avatar_`).
  String get assetPath => 'assets/avatars/$id.svg';
}

/// 11 cartoon avatars generated by Claude Design (256×256 SVGs in
/// assets/avatars/). 3 are free for everyone; the remaining 8 are Pro.
const figusAvatars = <FigusAvatar>[
  // ── free (3) ─────────────────────────────────────────────────────────────
  FigusAvatar(id: 'avatar_01', label: 'Ondulada',     proOnly: false),
  FigusAvatar(id: 'avatar_02', label: 'Barba',        proOnly: false),
  FigusAvatar(id: 'avatar_03', label: 'Franja',       proOnly: false),

  // ── pro (8) ──────────────────────────────────────────────────────────────
  FigusAvatar(id: 'avatar_04', label: 'Óculos',       proOnly: true),
  FigusAvatar(id: 'avatar_05', label: 'Headband',     proOnly: true),
  FigusAvatar(id: 'avatar_06', label: 'Bandana',      proOnly: true),
  FigusAvatar(id: 'avatar_07', label: 'Afro',         proOnly: true),
  FigusAvatar(id: 'avatar_08', label: 'Veterano',     proOnly: true),
  FigusAvatar(id: 'avatar_09', label: 'Pequena',      proOnly: true),
  FigusAvatar(id: 'avatar_10', label: 'Careca',       proOnly: true),
  FigusAvatar(id: 'avatar_11', label: 'Neutro',       proOnly: true),
];

/// Default avatar id used for new profiles + existing rows after migration.
const kDefaultAvatarId = 'avatar_01';

/// Renders a stored avatar identifier. If it matches an SVG asset (cartoon
/// avatars), renders the SVG; otherwise falls back to rendering it as plain
/// text — covers the emoji avatars from the previous MVP and any legacy data.
class AvatarImage extends StatelessWidget {
  final String id;
  final double size;
  const AvatarImage({super.key, required this.id, this.size = 48});

  @override
  Widget build(BuildContext context) {
    if (id.startsWith('avatar_')) {
      return SizedBox(
        width: size,
        height: size,
        child: SvgPicture.asset(
          'assets/avatars/$id.svg',
          width: size,
          height: size,
          // SVG is round on its own (a filled circle as the bg) — no need
          // to clip.
        ),
      );
    }
    // Legacy emoji avatar — render as text.
    return SizedBox(
      width: size,
      height: size,
      child: Center(
        child: Text(
          id,
          style: TextStyle(fontSize: size * 0.7),
        ),
      ),
    );
  }
}
