/// Mapping from Panini's 3-letter country code → ISO 3166-1 alpha-2,
/// used by the country_flags package to render SVG flags.
const Map<String, String> paniniToIso2 = {
  'ALG': 'DZ',
  'ARG': 'AR',
  'AUS': 'AU',
  'AUT': 'AT',
  'BEL': 'BE',
  'BIH': 'BA',
  'BRA': 'BR',
  'CAN': 'CA',
  'CIV': 'CI',
  'COD': 'CD',
  'COL': 'CO',
  'CPV': 'CV',
  'CRO': 'HR',
  'CUW': 'CW',
  'CZE': 'CZ',
  'ECU': 'EC',
  'EGY': 'EG',
  'ENG': 'GB-ENG',
  'ESP': 'ES',
  'FRA': 'FR',
  'GER': 'DE',
  'GHA': 'GH',
  'HAI': 'HT',
  'IRN': 'IR',
  'IRQ': 'IQ',
  'JOR': 'JO',
  'JPN': 'JP',
  'KOR': 'KR',
  'KSA': 'SA',
  'MAR': 'MA',
  'MEX': 'MX',
  'NED': 'NL',
  'NOR': 'NO',
  'NZL': 'NZ',
  'PAN': 'PA',
  'PAR': 'PY',
  'POR': 'PT',
  'QAT': 'QA',
  'RSA': 'ZA',
  'SCO': 'GB-SCT',
  'SEN': 'SN',
  'SUI': 'CH',
  'SWE': 'SE',
  'TUN': 'TN',
  'TUR': 'TR',
  'URU': 'UY',
  'USA': 'US',
  'UZB': 'UZ',
};

/// Portuguese nation name keyed by Panini code. Used wherever we want to
/// sort by selecção alfabetically — code-based sort would put "GER"
/// before "MEX" (G < M) but the user thinks "Alemanha" comes before
/// "México" by name.
const Map<String, String> nationNamePtByCode = {
  'ALG': 'Argélia',
  'ARG': 'Argentina',
  'AUS': 'Austrália',
  'AUT': 'Áustria',
  'BEL': 'Bélgica',
  'BIH': 'Bósnia',
  'BRA': 'Brasil',
  'CAN': 'Canadá',
  'CIV': 'Costa do Marfim',
  'COD': 'Congo',
  'COL': 'Colômbia',
  'CPV': 'Cabo Verde',
  'CRO': 'Croácia',
  'CUW': 'Curaçao',
  'CZE': 'República Tcheca',
  'ECU': 'Equador',
  'EGY': 'Egito',
  'ENG': 'Inglaterra',
  'ESP': 'Espanha',
  'FRA': 'França',
  'GER': 'Alemanha',
  'GHA': 'Gana',
  'HAI': 'Haiti',
  'IRN': 'Irã',
  'IRQ': 'Iraque',
  'JOR': 'Jordânia',
  'JPN': 'Japão',
  'KOR': 'Coreia do Sul',
  'KSA': 'Arábia Saudita',
  'MAR': 'Marrocos',
  'MEX': 'México',
  'NED': 'Holanda',
  'NOR': 'Noruega',
  'NZL': 'Nova Zelândia',
  'PAN': 'Panamá',
  'PAR': 'Paraguai',
  'POR': 'Portugal',
  'QAT': 'Catar',
  'RSA': 'África do Sul',
  'SCO': 'Escócia',
  'SEN': 'Senegal',
  'SUI': 'Suíça',
  'SWE': 'Suécia',
  'TUN': 'Tunísia',
  'TUR': 'Turquia',
  'URU': 'Uruguai',
  'USA': 'Estados Unidos',
  'UZB': 'Uzbequistão',
};

